name: flitter
description: A new flutter project.
version: 0.0.1

dependencies:
  flutter:
    sdk: flutter
  intl: '^0.14.0'
  http: "^0.11.3+13"
  jaguar_serializer: ^0.3.0
  flutter_webview_plugin:
    git: git@github.com:dart-flitter/flutter_webview_plugin.git

flutter:
  uses-material-design: true
  assets:
    - assets/html/success.html
    - assets/images/banner.jpg
