name: flitter
description: A new flutter project.

dependencies:
  flutter:
    sdk: flutter
  intl: '^0.14.0'
  http: "^0.11.3+13"
  jaguar_serializer: ^0.3.0
  flutter_webview_plugin:
      path: flutter_webview_plugin

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the Icons class.
  uses-material-design: true

  assets:
    - assets/html/success.html
    - assets/images/banner.jpg
