name: flitter
description: A new flutter project.
version: 0.0.1

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.14.0
  http: ^0.11.3+13
  jaguar_serializer: ^0.3.0
  flutter_webview_plugin: ^0.0.3
  redux: ^1.1.0
  shared_preferences: ">=0.2.0 <1.0.0"
  url_launcher: ">=0.4.0 <1.0.0"
  gitter:
    git: git@github.com:dart-flitter/gitter_dart.git

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/html/success.html
    - assets/images/banner.jpg
